name: copter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.9+10

environment:
  sdk: ">=2.18.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  percent_indicator: ^4.0.0
  expandable_text: ^2.2.0
  flutter_switch: ^0.3.2
  flutter_rating_bar: ^4.0.0
  sliver_tools: ^0.2.5
  dotted_border: ^2.0.0+2
  flutter_calendar_carousel: ^2.1.0
  intl: ^0.17.0
  animated_bottom_navigation_bar: ^1.1.0
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  cloud_firestore: ^3.5.1
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.2
  file_picker: ^5.2.1
  firebase_storage: ^10.3.11
  firebase_messaging: ^13.1.0
  flutter_local_notifications: ^12.0.3
  timeago: ^3.3.0
  in_app_purchase: ^3.0.8
  dio: ^4.0.6
  flutterfire_ui: ^0.4.3+14
  image_picker: ^0.8.6
  flutter_downloader: ^1.9.1
  path_provider: ^2.0.11
  external_path: ^1.0.3
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    -  assets/images/
    -  assets/images/dummy_chat/
    -  assets/images/dummy_files/
    -  assets/images/dummy_public_accounts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
